version: '3'
services:
  aimm:
    container_name: aimm
    ports:
      - 5000:5000
    environment:
      - REDIS_HOST=redis-99999.redis.url.com
      - REDIS_PORT=99999
      - REDIS_PASSWORD=password
    volumes:
      - C:/Users/steph/.cache/downloadImage/target_folder:/app/static/ImgStore
    image: aimm