version: '3'
services:
  aimm:
    container_name: aimm
    ports:
      - 5000:5000
    environment:
      - REDIS_Host=""
      - REDIS_PORT=""
      - REDIS_PASSWORD=""
    volumes:
      - C:/Users/steph/.cache/downloadImage/target_folder:/app/static/ImgStore
    image: aimm